# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Principal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 671)
        MainWindow.setMinimumSize(QtCore.QSize(1197, 671))
        MainWindow.setMaximumSize(QtCore.QSize(1197, 671))
        MainWindow.setStyleSheet("background-color: #130F1A;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FF944D;\n"
"border-bottom:3px solid #FF944D;\n"
"padding:2px;")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 280, 261, 261))
        self.frame.setStyleSheet("background-image: url(mundo1.png);\n"
"background-repeat: no-repeat;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(190, 200, 71, 81))
        self.frame_2.setStyleSheet("background-image: url(aviao(1).png);\n"
"background-repeat: no-repeat;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 620, 71, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: rgb(198, 70, 0);\n"
"color: black;\n"
"border-radius: 10px;}\n"
"\n"
"QPushButton:hover {\n"
"background-color: white;\n"
"color: black;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(520, 110, 241, 161))
        self.frame_3.setStyleSheet("border: 1px solid white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.label_2.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label_3.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.label_4.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.label_5.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(120, 20, 101, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(120, 50, 101, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(120, 80, 101, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(130, 120, 101, 17))
        self.label_9.setObjectName("label_9")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(880, 110, 241, 161))
        self.frame_4.setStyleSheet("border: 1px solid white;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.label_10.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label_11.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.label_12.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.label_13.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(120, 20, 101, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(120, 50, 101, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(120, 80, 101, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(130, 120, 101, 17))
        self.label_17.setObjectName("label_17")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(690, 290, 241, 161))
        self.frame_5.setStyleSheet("border: 1px solid white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.label_18.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label_19.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.label_20.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.label_21.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(120, 20, 101, 17))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(120, 50, 101, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(120, 80, 101, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(130, 120, 101, 17))
        self.label_25.setObjectName("label_25")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(500, 470, 241, 161))
        self.frame_6.setStyleSheet("border: 1px solid white;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.label_26.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label_27.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.label_28.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.label_29.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(120, 20, 101, 17))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(120, 50, 101, 17))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_6)
        self.label_32.setGeometry(QtCore.QRect(120, 80, 101, 17))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_6)
        self.label_33.setGeometry(QtCore.QRect(130, 120, 101, 17))
        self.label_33.setObjectName("label_33")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(850, 470, 241, 161))
        self.frame_7.setStyleSheet("border: 1px solid white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_34 = QtWidgets.QLabel(self.frame_7)
        self.label_34.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.label_34.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_7)
        self.label_35.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label_35.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_7)
        self.label_36.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.label_36.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_7)
        self.label_37.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.label_37.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_7)
        self.label_38.setGeometry(QtCore.QRect(120, 20, 101, 17))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame_7)
        self.label_39.setGeometry(QtCore.QRect(120, 50, 101, 17))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_7)
        self.label_40.setGeometry(QtCore.QRect(120, 80, 101, 17))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_7)
        self.label_41.setGeometry(QtCore.QRect(130, 120, 101, 17))
        self.label_41.setObjectName("label_41")
        self.label.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.pushButton_3.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Flight Price"))
        self.pushButton_3.setText(_translate("MainWindow", "Sair"))
        self.label_2.setText(_translate("MainWindow", "Companhia:"))
        self.label_3.setText(_translate("MainWindow", "Preço:"))
        self.label_4.setText(_translate("MainWindow", "Desembarque:"))
        self.label_5.setText(_translate("MainWindow", "Embarque:"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Companhia:"))
        self.label_11.setText(_translate("MainWindow", "Preço:"))
        self.label_12.setText(_translate("MainWindow", "Desembarque:"))
        self.label_13.setText(_translate("MainWindow", "Embarque:"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "Companhia:"))
        self.label_19.setText(_translate("MainWindow", "Preço:"))
        self.label_20.setText(_translate("MainWindow", "Desembarque:"))
        self.label_21.setText(_translate("MainWindow", "Embarque:"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "Companhia:"))
        self.label_27.setText(_translate("MainWindow", "Preço:"))
        self.label_28.setText(_translate("MainWindow", "Desembarque:"))
        self.label_29.setText(_translate("MainWindow", "Embarque:"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.label_31.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "Companhia:"))
        self.label_35.setText(_translate("MainWindow", "Preço:"))
        self.label_36.setText(_translate("MainWindow", "Desembarque:"))
        self.label_37.setText(_translate("MainWindow", "Embarque:"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.label_39.setText(_translate("MainWindow", "TextLabel"))
        self.label_40.setText(_translate("MainWindow", "TextLabel"))
        self.label_41.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Principal()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
